notifications:
    - provider: Email
      on_build_success: false

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\okhttp-fork
shallow_clone: true

build:
    parallel: true

matrix:
    fast_finish: false

environment:
    OPENSSL_ROOT_DIR: C:\OpenSSL-Win64
    matrix:
        - BUILD_SHARED_LIBS: ON
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        - BUILD_SHARED_LIBS: ON
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
        - BUILD_SHARED_LIBS: OFF
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        - BUILD_SHARED_LIBS: OFF
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

configuration:
    - Debug
    - Release

build_script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DBUILD_SHARED_LIBS=%BUILD_SHARED_LIBS% -DDTLS=ON
    - cmake --build .

test_script:
    - cd tests
    - cd %CONFIGURATION%
    - .\ohf_tests.exe