dist: trusty
sudo: required

notifications:
  email:
    on_success: never
    on_failure: always

language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - gcc-5
      - g++-5

env:
  - BUILD_CONFIGURATION=Debug BUILD_SHARED=ON
  - BUILD_CONFIGURATION=Release BUILD_SHARED=ON
  - BUILD_CONFIGURATION=Debug BUILD_SHARED=OFF
  - BUILD_CONFIGURATION=Release BUILD_SHARED=OFF

script:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DBUILD_SHARED=$BUILD_SHARED
  - sudo make install -j4
