dist: trusty
sudo: required

language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r/test
    packages:
      - g++-5
      - libssl-dev

env:
  - BUILD_CONFIGURATION=Debug BUILD_SHARED=ON
  - BUILD_CONFIGURATION=Release BUILD_SHARED=ON
  - BUILD_CONFIGURATION=Debug BUILD_SHARED=OFF
  - BUILD_CONFIGURATION=Release BUILD_SHARED=OFF

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DBUILD_SHARED=$BUILD_SHARED
  - cmake --build .
